# Generated by Django 4.1.1 on 2022-09-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("price", models.PositiveIntegerField(verbose_name="price")),
                ("image", models.URLField(verbose_name="image")),
                (
                    "release_date",
                    models.ImageField(upload_to="", verbose_name="release_date"),
                ),
                ("lte_exists", models.BooleanField()),
                ("slug", models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
