# Generated by Django 4.1.1 on 2022-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="release_date",
            field=models.DateField(verbose_name="release_date"),
        ),
    ]
